# TODO: window still does not work. Only sessions do.

[default_session]
startup_command = "yazi"

[[session]]
name = "dragon üêâ"
path = "~/Library/Mobile Documents/iCloud~md~obsidian/Documents/dragon"
startup_command = "tmux rename-window 'dragon'; yazi"

[[session]]
name = "drafts üìé"
path = "~/Library/Mobile Documents/iCloud~md~obsidian/Documents/drafts"
startup_command = "tmux rename-window 'drafts'; yazi"

[[session]]
name = "downloads üì•"
path = "~/Downloads"
startup_command = "tmux rename-window 'download'; yazi"

# [[window]]
# name = "rfqs"
# path = "~/Library/CloudStorage/OneDrive-SharedLibraries-JasonElectronicsPteLtd/Bid Proposal - Documents/@rfqs"
# startup_command = "tmux rename-window 'rfqs'"

# '@' symbols in name needs to be escaped. Not advisable to use.
[[session]]
name = "docs üìö"
path = "~/Library/CloudStorage/OneDrive-SharedLibraries-JasonElectronicsPteLtd/Bid Proposal - Documents/@docs"
startup_command = "tmux rename-window 'docs'; yazi"
# windows = ["rfqs"]

[[session]]
name = "dotfiles"
path = "~/Repos/github.com/tittitoo/dotfiles"
startup_command = "tmux rename-window 'dotfiles'; yazi"

[[session]]
name = "handover"
path = "~/Library/CloudStorage/OneDrive-SharedLibraries-JasonElectronicsPteLtd/Bid Proposal - Documents/@handover"
startup_command = "tmux rename-window 'handover'; yazi"

[[session]]
name = "costing"
path = "~/Library/CloudStorage/OneDrive-SharedLibraries-JasonElectronicsPteLtd/Bid Proposal - Documents/@costing"
startup_command = "tmux rename-window 'costing'; yazi"

[[session]]
name = "tmux"
path = "~/Repos/github.com/tittitoo/dotfiles/tmux/.config/tmux"
startup_command = "tmux rename-window 'tmux'; nvim tmux.conf"

[[session]]
name = "minimalist"
path = "~/Repos/github.com/tittitoo/minimalist"
startup_command = "tmux rename-window 'minimalist'; yazi"

[[session]]
name = "journal"
path = "~/Library/Mobile Documents/iCloud~md~obsidian/Documents/journal"
startup_command = "tmux rename-window 'journal'; yazi"

[[session]]
name = "team"
path = "~/Library/Mobile Documents/iCloud~md~obsidian/Documents/team"
startup_command = "tmux rename-window 'team'; yazi"

[[session]]
name = "btop"
path = "~/Downloads"
startup_command = "tmux rename-window 'btop'; btop"

[[session]]
name = "ghostty"
path = "~/Repos/github.com/tittitoo/dotfiles/ghostty/.config/ghostty"
startup_command = "tmux rename-window 'ghostty'; nvim config"

[[session]]
name = "rfqs"
path = "~/Library/CloudStorage/OneDrive-SharedLibraries-JasonElectronicsPteLtd/Bid Proposal - Documents/@rfqs"
startup_command = "tmux rename-window 'rfqs'"
