# TODO: window still does not work. Only sessions do.

[default_session]
startup_command = "yazi"

[[session]]
name = "programming "
path = "~/Repos/github.com/tittitoo/minimalist"
startup_command = """
tmux rename-window 'minimalist'; 
tmux new-window -n 'scripts' -c "~/Repos/github.com/tittitoo/minimalist/scripts";
"""

[[session]]
name = "dragon ğŸ²"
path = "~/Library/Mobile Documents/iCloud~md~obsidian/Documents/dragon"
startup_command = "tmux rename-window 'dragon ğŸ²'; yazi"

[[session]]
name = "drafts ğŸ“"
path = "~/Library/Mobile Documents/iCloud~md~obsidian/Documents/drafts"
startup_command = "tmux rename-window 'drafts ğŸ“'; yazi"

[[session]]
name = "downloads ğŸ“¥"
path = "~/Downloads"
startup_command = "tmux rename-window 'download ğŸ“¥'; yazi"

[[session]]
name = "rfqs ğŸ¥š"
path = "~/Library/CloudStorage/OneDrive-SharedLibraries-JasonElectronicsPteLtd/Bid Proposal - Documents/@rfqs"
startup_command = "tmux rename-window 'rfqs ğŸ¥š'; clear"

# [[window]]
# name = "rfqs"
# path = "~/Library/CloudStorage/OneDrive-SharedLibraries-JasonElectronicsPteLtd/Bid Proposal - Documents/@rfqs"
# startup_command = "tmux rename-window 'rfqs'"

# '@' symbols in name needs to be escaped. Not advisable to use.
[[session]]
name = "docs ğŸ“š"
path = "~/Library/CloudStorage/OneDrive-SharedLibraries-JasonElectronicsPteLtd/Bid Proposal - Documents/@docs"
startup_command = "tmux rename-window 'docs ğŸ“š'; yazi"
# windows = ["rfqs"]

[[session]]
name = "dotfiles"
path = "~/Repos/github.com/tittitoo/dotfiles"
startup_command = "tmux rename-window 'dotfiles'; yazi"

[[session]]
name = "handover"
path = "~/Library/CloudStorage/OneDrive-SharedLibraries-JasonElectronicsPteLtd/Bid Proposal - Documents/@handover"
startup_command = "tmux rename-window 'handover'; yazi"

[[session]]
name = "costing"
path = "~/Library/CloudStorage/OneDrive-SharedLibraries-JasonElectronicsPteLtd/Bid Proposal - Documents/@costing"
startup_command = "tmux rename-window 'costing'; yazi"

[[session]]
name = "tmux"
path = "~/Repos/github.com/tittitoo/dotfiles/tmux/.config/tmux"
startup_command = "tmux rename-window 'tmux'; nvim tmux.conf"

[[session]]
name = "minimalist"
path = "~/Repos/github.com/tittitoo/minimalist"
startup_command = "tmux rename-window 'minimalist'; yazi"

[[session]]
name = "journal"
path = "~/Library/Mobile Documents/iCloud~md~obsidian/Documents/journal"
startup_command = "tmux rename-window 'journal'; yazi"

[[session]]
name = "team"
path = "~/Library/Mobile Documents/iCloud~md~obsidian/Documents/team"
startup_command = "tmux rename-window 'team'; yazi"

[[session]]
name = "btop"
path = "~/Downloads"
startup_command = "tmux rename-window 'btop'; btop"

[[session]]
name = "ghostty"
path = "~/Repos/github.com/tittitoo/dotfiles/ghostty/.config/ghostty"
startup_command = "tmux rename-window 'ghostty'; nvim config"
